name: Poify/Unpoify/dir2msgstr
on:
  push:
    paths:
      - "WeiDU-Weblate-GitHub/Languages/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Poify/Unpoify/dir2msgstr
        uses: ALIENQuake/msg2po@master
        with:
          poify: true
          unpoify: true
          unpoify_utf8: true
          push: true
          single_commit: false
          dir2msgstr: true
